[[plugins]]
repo = 'Shougo/neocomplete'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'
on_ft = ['typescript']

[[plugins]]
repo = 'wakatime/vim-wakatime'
on_i = 1

